//template

//ascii value to char
char a = (char) 48 //returns character 0

//char to ascii value
int a = (int) 'a' //returns 97

//char to int
int a = (int)'0'-48;//returns int 0

//int to char
char a = (char) (0+48)//returns char 0

//int to string
String s = String.valueOf(number)

//string to int
int foo = Integer.parseInt("1234");

//double to string
String t = String.valueOf(double_number);

//strint to double
String text = "12.34"; // example String
double value = Double.parseDouble(text);

//string to chararray
char[] charArray = str.toCharArray();

//chararray to string
char[] charArray = {'a', 'b', 'c'};
String str = String.valueOf(charArray);


//shortcut to print arrays in java
Arrays.deepToString(twoDimensionArray));
          OR
for(int i : iArray){
   System.out.print(i +", ");
}


//PRINTING ARRAYLIST IN JAVA
for (String[] p : stringo){
    System.out.println(Arrays.deepToString(p));
	System.out.println();
	}
		  

//SPLIITTING TEXT INTO SPACE SEPARATED WORD ARRAY
String[] s = string.trim().split("\\s++")

//charat string
 char result = s.charAt(8);
 
 
 
 //index of str
 Str.indexOf( 'o' )